### ISSUE TITLE
Create a FAQ page

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#9] opened 2020-03-23 03:37 UTC
Related source code: components/SideNavigation.vue

Here is the FAQ list.
https://docs.google.com/spreadsheets/d/1_wBXS62S5oBQrwetGc8_-dFvDjEmNqzqHwUeP-DzkYs/edit#gid=0

**Comment by frhino** [comment] 2020-04-04 20:32
Closing this as duplicate of https://github.com/sfbrigade/stop-covid19-sfbayarea/issues/13

**Closed by frhino** 2020-04-04 20:32 UTC
